const sections = [
  {
    id: "how-grading-works",
    title: "How grading works",
    body: [
      "Every listing on Renew ships with a diagnostic report generated by our bench-testing script, not a seller's guess at condition.",
      "Grades (A/B/C) map to hours logged, thermal wear, and boot stability, and every listing shows the raw benchmark score and tested power draw alongside the grade — so you're buying off data, not photos.",
    ],
  },
  {
    id: "buyer-protection",
    title: "Buyer protection",
    body: [
      "Every order goes through escrow. Payment is held until you confirm the item you received matches its diagnostic report.",
      "If it doesn't match, you can open a dispute before funds release to the seller, and Renew will step in to resolve it.",
    ],
  },
  {
    id: "return-policy",
    title: "Return policy",
    body: [
      "Every purchase comes with a 7-day return window. Bench the item yourself against the diagnostic report on the listing.",
      "If the numbers don't match — grade, benchmark score, or power draw — send it back for a full refund.",
    ],
  },
];

export default function FaqPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-20">
      <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-amber mb-4">
        Trust
      </p>
      <h1 className="font-display font-semibold text-3xl mb-12">
        Frequently asked questions
      </h1>
      <div className="space-y-14">
        {sections.map((section) => (
          <section key={section.id} id={section.id} className="scroll-mt-24">
            <h2 className="font-display font-medium text-xl mb-4">
              {section.title}
            </h2>
            <div className="space-y-4 text-ink-dim text-[15px] leading-relaxed">
              {section.body.map((paragraph) => (
                <p key={paragraph}>{paragraph}</p>
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
